### ISSUE TITLE
Add report command to show a week's standups for a user

### ISSUE THREAD

**Issue by lauraGgit** [18F/standup-bot#13] opened 2016-02-19 21:58 UTC
Standups help me jog my memory for tock. The bot may make it easier through by just having a list of DMs or it may make it harder to find my own standups. I'm not sure what solution I'm proposing, I would just like to still be able to find my weeks' standups.

**Comment by stvnrlly** [comment] 2016-02-20 16:50
Definitely. Storing the standups in a database should make some sort of `@standupbot report` command possible.

What sort of report would be useful to you? Would it mostly be the "Yesterday" entries related to the period, or would something else help?

**Comment by vdavez** [comment] 2016-04-26 17:20
I made a card with a specific user story to describe this scenario. https://github.com/18F/standup-bot/issues/56 @lauraGgit, does this capture what you're thinking?

**Comment by lauraGgit** [comment] 2016-04-26 18:04
@vzvenyach that looks like what I am thinking.

**Comment by vdavez** [comment] 2016-05-09 14:27
Duplicate of #56.

**Closed as completed by vdavez** 2016-05-09 14:27 UTC
Labels: duplicate
